### ISSUE TITLE
Adding t-SNE from sklearn.manifold

### ISSUE THREAD

**Issue by Mayanksoni20** [8080labs/pyforest#7]
### Description of Issue
I wanted to add t-SNE from sklearn.manifold. Please let me know this is valid and i will create a pull request. I can add more classification and regression algorithms like Random Forest and XGboost but wanted to know if they are required in something like "from pyforest import classifiers (this contains all classifiers)" or something like "from pyforest import randomforest" or this will be included in "from sklearn import * "
...

**Comment by FlorianWetschoreck** [comment]
Hi,
thank you for contributing and for opening the issue before opening a pull request.
Our goal is to provide the statements in the "typical, conventional way". So basically it should be the answer to:
"How did you import tSNE in your last script?"

According to the scikit-learn docs it would be:
from sklearn.manifold import TSNE

Is this also how you did use it?
Then I suggest to add it exactly like this:
TSNE = LazyImport("from sklearn.manifold import TSNE")

The same for the other imports. We always try to provide the conventional best practice as long as there are no overlaps.

Please note that we will not support general imports like "from sklearn import *" in order to be able to explicitly manage the available names and detect possible collisions.

**Comment by Mayanksoni20** [comment]
Alright. I will add and open a pull request.

**Comment by FlorianWetschoreck** [comment]
Great, looking forward to it :)

**Comment by Mayanksoni20** [comment]
Done :) Please let me know if its in the correct format, next up i will add some clustering stuff and error metrics. Maybe Linear and Logistic regression too.

**Comment by Mayanksoni20** [comment]
Hi Florian, Any update on the pull request ?

**Comment by FlorianWetschoreck** [comment]
Hi, we are currently super busy on bamboolib. Since there are a couple of pull requests, we will hopefully review them all in one session at least by the end of this week. :)

**Comment by Mayanksoni20** [comment]
Sure, I can see that the the PR has now been merged. Closing this issue.
